#!/bin/sh

echo "building pkg"

go build $1 language
go install language

echo "building executables"

go build $1 -o bin/main src/main.go
go build $1 -o bin/model_build src/model_build.go

echo "done."
